// <auto-generated />
using ClikerGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClikerGame.Data.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230929140557_ModifiersAdded")]
    partial class ModifiersAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("ClikerGame.Data.UserModel+Modifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Modificator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Modifier", null, t =>
                        {
                            t.HasCheckConstraint("Name", "Name <> ''");
                        });
                });

            modelBuilder.Entity("ClikerGame.Data.UserModel+User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityOfModifiers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("Nickname", "Nickname <> ''");
                        });
                });

            modelBuilder.Entity("ModifierUser", b =>
                {
                    b.Property<int>("GamersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModifiersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GamersId", "ModifiersId");

                    b.HasIndex("ModifiersId");

                    b.ToTable("ModifierUser");
                });

            modelBuilder.Entity("ModifierUser", b =>
                {
                    b.HasOne("ClikerGame.Data.UserModel+User", null)
                        .WithMany()
                        .HasForeignKey("GamersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClikerGame.Data.UserModel+Modifier", null)
                        .WithMany()
                        .HasForeignKey("ModifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
